from fastapi import APIRouter
from pydantic import BaseModel
from typing import List, Dict, Any, Optional
from backend.utils.chart_planner import plan_charts_from_preview
from backend.utils.quickchart_builder import build_quickchart_url
from backend.utils.dashboard_composer import compose_dashboard_from_urls
from backend.utils.pdf_exporter import export_pdf
from backend.utils.bi_exporter import export_csv_from_preview, powerbi_theme_json
import json
import os
import base64

router = APIRouter()

class AutoRequest(BaseModel):
    preview: List[Dict[str, Any]]
    theme_id: str = "minimal_white"
    title: str = "Insightify Auto Dashboard"
    user_id: Optional[str] = None

@router.post("/auto-dashboard")
def auto_dashboard(req: AutoRequest):
    try:
        # 1. Plan charts
        plan = plan_charts_from_preview(req.preview, max_charts=4)

        # 2. Load theme file
        themes_file = os.path.join(os.path.dirname(__file__), "../themes/themes.json")
        with open(themes_file, "r") as f:
            themes = json.load(f)

        theme = next((t for t in themes if t["id"] == req.theme_id), themes[0])

        chart_urls = []
        charts_meta = []

        for item in plan:
            # Build natural language description
            if item["chart_type"] == "kpi":
                desc = f"kpi showing {item['description']}"
                url = build_quickchart_url(desc, data=[item["value"]], theme=theme, width=600, height=200)
            elif item["chart_type"] == "bar":
                desc = f"bar chart showing {item['description']}"
                url = build_quickchart_url(desc, labels=item.get("labels", []), data=item.get("data", []), theme=theme, width=800, height=400)
            elif item["chart_type"] == "line":
                desc = f"line chart showing {item['description']}"
                url = build_quickchart_url(desc, labels=item.get("labels", []), data=item.get("data", []), theme=theme, width=800, height=400)
            elif item["chart_type"] == "scatter":
                desc = f"scatter plot showing {item['description']}"
                # For scatter, we need x and y data
                # This is simplified - in practice you'd need to extract x,y from preview
                url = build_quickchart_url(desc, theme=theme, width=800, height=400)
            else:
                continue

            if url:
                chart_urls.append(url)
                charts_meta.append({"url": url, "spec": item, "type": item.get("chart_type"), "title": item.get("description")})

        # 3. Compose dashboard image
        dashboard_buf = compose_dashboard_from_urls(chart_urls, title=req.title)

        # 4. PDF export
        summary_text = "Auto-generated by Insightify"
        pdf_buf = export_pdf(req.title, summary_text, chart_urls, dashboard_buf)

        # 5. CSV export
        csv_bytes = export_csv_from_preview(req.preview)

        # 6. Power BI theme JSON
        theme_json = powerbi_theme_json(theme)

        # 7. Encode binary files to Base64
        dash_b64 = base64.b64encode(dashboard_buf.getvalue()).decode("utf-8")
        pdf_b64 = base64.b64encode(pdf_buf.getvalue()).decode("utf-8")
        csv_b64 = base64.b64encode(csv_bytes).decode("utf-8") if csv_bytes else None

        return {
            "theme": theme,
            "charts": charts_meta,
            "dashboard_png_b64": dash_b64,
            "pdf_b64": pdf_b64,
            "csv_b64": csv_b64,
            "powerbi_theme_json": theme_json,
        }

    except Exception as e:
        return {"error": True, "message": str(e)}
